### ISSUE TITLE
[vite:css] Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by rasteiner** [johannschopplich/kirbyup#14] opened 2022-04-29 13:03 UTC
I'm getting an error like this:

```
[vite:css] Cannot read properties of undefined (reading 'config')
file: /path/to/project/site/plugins/packer/src/components/Packer.vue?vue&type=style&index=0&lang.css

 ERROR  Build failed  
```

When running from the default Kirby plugin creator kit (`kirbyup src/index.js --watch`, and `kirbyup src/index.js`).

This starts happening once I add a `<style>` tag to a Vue SFC that I import into `src/index,js`. 
I did not add any custom configuration and it's a pretty much standard plugin setup:
<img width="110" alt="image" src="https://user-images.githubusercontent.com/6684137/165949045-b467e672-5cf2-4085-832f-6287f8a3d8ac.png">

Node version: v16.13.2
Kirbyup version: kirbyup/0.23.0 

----

Don't know if this matters; the plugin is inside a  `site/plugins` folder of a kirby site that has `postcss.config.js` `tailwind.config.js` files in the root directory. The plugin however does *not* use or rely on them. (Simply there are such files in a parent directory). 

How can I help debug this better?

**Comment by rasteiner** [comment] 2022-04-30 16:04
Looks like kirbyup is influenced by the postcss.config.js in the project root. 
Here more info: https://forum.getkirby.com/t/custom-block-single-file-component-error/25173

**Comment by johannschopplich** [comment] 2022-06-01 12:07
Hi Roman,
thanks for the bug report. Indeed, [postcss-load-config](https://github.com/postcss/postcss-load-config) will walk up the parent directory until the executing directory is reached. At least it should work that way. Did you run `kirbyup` from the `packer` directory or did you call it from the project's root?
I may have to force the PostCSS loader to stick to the executing path.

**Comment by jonaskuske** [comment] 2023-04-07 12:34
Given that it *should* work based on the `cwd`, I'll close this for now. If you still run into this problem, please provide a reproduction and we can re-open and fix the issue :)

**Comment by ovenum** [comment] 2023-06-14 15:11
Can confirm that it will actually load postcss config from parent directories which can prevent kirbyup from working when postcss plugins are not installed.

This can have unintended side effects depending on where the plugin is compiled by kirbyup. (Development happening in between two different kirby installations for example)

To reproduce just setup a barebones structure with a package.json in the project root.

```markdown
├── site
│   ├── plugins
│   ├── myPlugin
│   │   ├── src
│   │   │   ├── index.js
│   │   ├── package.json
├── package.json  __kirbyup will try to load postcss settings from here__
```

```js
// package.json from project root
"postcss": {
  "plugins": {
     "autoprefixer": true
  }
}

// /site/plugins/myPlugin/package.json
{
  "scripts": {
      "dev": "npx -y kirbyup src/index.js --watch ",
      "build": "npx -y kirbyup src/index.js"
   },
  "devDependencies": {
    "kirbyup": "^0.22.2"
  }
}
```

**kirbyup**: v.2.2.1

**Comment by ovenum** [comment] 2023-06-19 15:26
Thanks for looking into this again @jonaskuske. 
I think what tripped me was that the readme says that it will auto apply a postCss config if no postCss config is specified for the plugin and i was just fine with that.
My current work around is to just add an empty postCss property to the plugins package.json to stop resolving of parent directories but this might have overwritten kirbyups defaults(?)

Maybe a hint in the readme how to just load the kirbyups default is enough?

**Comment by jonaskuske** [comment] 2023-06-19 16:08
Yup, an empty config replaces kirbyup's default :(

We could check for empty configs and keep applying the default, but then disabling the defaults isn't possible anymore. I think preventing the lookup in parent directories via `stopDir` is the best way, released as a v3. cc @johannschopplich

**Comment by johannschopplich** [comment] 2023-06-19 16:16
I agree. Walking up the directories until a PostCSS config file is found feels like more implicit magic than a best-practice default. Most users (myself included) didn't even know this was happening.

Releasing v3 to control this breaking change seems like the best way. I'm in! 👍 

Thank you both for tracking this issue. 🌻

**Closed** 2023-06-20 13:05 UTC
